config/routes.rb
EpisodeTracker::Application.routes.draw do

  get "admin_config/show"
  get "admin_config/search"
  get "admin_config/search_remote"
  get "admin_config/confirm_search"
  post "admin_config/update"

  match "episodes/create" => "episodes#create"
  devise_for :users
  get "pages/home"

  resources :user_episodes

  get "series/search"
  resources :series do
    resources :episodes
  end

  root :to => 'pages#home'

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :series, primary_key: :remote_id
  has_many :user_episodes
  has_many :users, through: :user_episodes
  validates_presence_of :name
  attr_accessible :name, :overview, :series_id, :season, :air_date, :remote_id
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource :only => [:create]

  def create
    authorize! :manage, :all
    @ac = ApiConnector.new
    @series = Series.where(:remote_id => params[:remote_id]).first
    if @series.episodes.present?
      flash[:alert] = "It looks like you already have the episodes for that series!"
    else
      episodes = @ac.get_episodes(params[:remote_id])
      episodes.each do |episode|
        name = episode.elements["EpisodeName"].text
        overview = episode.elements["Overview"].text
        season = episode.elements["SeasonNumber"].try(:text).to_i
        air_date = episode.elements["FirstAired"].try(:text) || '01/01/2100'.to_date
        remote_id = episode.elements["id"].text
        name.nil? ? name = "This episode has no name" : name
        Episode.create!(name: name, overview: overview, series_id: params[:remote_id], season: season, air_date: air_date, remote_id: remote_id)
      end
    end
    redirect_to series_episodes_path(@series)
  end

  def index
    @series = Series.find(params[:series_id])
    #@episodes = @series.episodes.paginate(:page => params[:page], :per_page => 10)
    @episodes_grouped_by_season = @series.episodes.sort_by(&:air_date).group_by(&:season).sort

    episodes =  @series.episodes.includes(:user_episodes)

    @user_episodes = {}
    episodes.each do | episode |
      user_episode = episode.user_episodes.first
      if user_episode && user_episode.user_id == current_user.id
        @user_episodes.merge!({ episode.id => episode.user_episodes.first })
      end
    end
    @user_episodes
  end
end

app/views/episodes/_checkbox_checked.html.erb
<%= form_for(:user_episode, url: "/user_episodes/#{user_episode.id}", method: "delete", remote: true ) do |f| %>
    <%= check_box_tag(:episode, episode_id, true, { :class => "submittable"} ) %>
<% end %>

app/views/episodes/_checkbox_unchecked.html.erb
<%= form_for(:user_episode, url: user_episodes_path, action: "create", method: "post", remote: true ) do |f| %>
    <%= check_box_tag(:episode, episode_id, false, { :class => "submittable"} ) %>
<% end %>

app/views/episodes/index.html.erb
<div class='page-header'>
  <h3>This is the episode list for <%= @series.name %></h3>
</div>
<h5><%= @series.overview %></h5>
</br>

<div class="panel-group" id="accordion">
    <% @episodes_grouped_by_season.each do |season, episodes| %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">
              <a href="#" data-toggle="collapse" data-parent="#accordion" data-target="#season<%= season %>">
                <% if season == 0 %>
                    Episodes without season information
                <% else %>
                    Season <%= season %>
              <% end %>
              </a>
            </h3>
          </div>
          <div id="season<%= season %>" class="panel-collapse collapse">
              <div class="panel-body">
                <table class="table table-striped">
                  <thead>
                  <tr>
                    <th>Air date</th>
                    <th>Episode title</th>
                    <th class="col-sm-2">Watched this episode?</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% episodes.each do |episode| %>
                      <tr>
                        <td><%= episode.air_date %></td>
                        <td><%= episode.name %></td>
                        <td>
                          <% if @user_episodes[episode.id].present? %>
                              <%= render partial: "checkbox_checked", locals: {user_episode: @user_episodes[episode.id], episode_id: episode.id} %>
                          <% else %>
                              <%= render partial: "checkbox_unchecked", locals: {episode_id: episode.id} %>
                          <% end %>
                        </td>
                      </tr>
                  <% end %>
                  </tbody>
                </table>
              </div>
          </div>
        </div>
    <% end %>
</div>