config/routes.rb
EpisodeTracker::Application.routes.draw do

  get "admin_config/show"
  get "admin_config/search"
  get "admin_config/search_remote"
  get "admin_config/confirm_search"
  post "admin_config/update"

  match "episodes/create" => "episodes#create"
  devise_for :users
  get "pages/home"

  resources :user_episodes

  get "series/search"
  resources :series do
    resources :episodes
  end

  root :to => 'pages#home'

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_filter :authenticate_user!
  rescue_from ActionController::RoutingError, :with => :not_found
  respond_to :json, only: [ :index ]

  def index
    @series = Series.search(params[:search])
  end
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_index.html.erb
<div class="extra-padding-top">
  <h4>Your search returned <%= pluralize(@series.length, 'result') %>:</h4>
      <%= render(:partial => 'series_list') %>
</div>

app/views/series/_select_for_show.html.erb
<h4>
  Your search returned <%= pluralize(@series.length, 'result') %>:
</h4>

<table class="table table-striped">
    <% @series.each do |series| %>
        <tr>
            <td>
                <%= series.name%>
            </td>
            <td>
                <%= form_tag("/episodes/create", :class => "inline-form right") do %>
                <%= hidden_field_tag :remote_id, series.remote_id %>
                <%= submit_tag "Get episodes", class: "btn btn-primary" %>
                <%end%>
            </td>
            </td>
        </tr>
    <% end %>
</table>

app/views/series/_series_list.html.erb
<div class="list-group">
  <% @series.each do |series| %>
      <a href="<%=series_episodes_path(series)%>" class="list-group-item"><%= series.name%></a>
  <% end %>
</div>

app/views/series/index.html.erb
<div>
  <h4>Your search returned <%= pluralize(@series.length, 'result') %>:</h4>
      <%= render(:partial => 'series_list') %>
</div>

app/views/series/index.js.erb
$('.js-search-results').html('<%= escape_javascript(render(partial: 'index')) %>');

app/views/series/search.html.erb
<div class="page-header" xmlns="http://www.w3.org/1999/html">
    <h3>Try the search box below to find a series</h3>
</div>
<div>
    <%= form_tag(series_index_path, method: "get", class: 'form-search', remote: true) do %>
        <%= label_tag :name, 'Look for a series by its name' %><br />
        <div class="input-group col-md-5">
            <%= text_field_tag :search, nil, placeholder: 'Search...', class: "form-control", autofocus: true %>
            <div class="input-group-btn">
                <%= submit_tag "Search", name: nil, :class => "btn-primary btn" %>
            </div>
        </div>
    <% end %>
  </br>
  </br>
  <div class="js-search-results">
  </div>
</div>