config/routes.rb
EpisodeTracker::Application.routes.draw do

  get "admin_config/show"
  get "admin_config/search"
  get "admin_config/search_remote"
  get "admin_config/confirm_search"
  post "admin_config/update"

  match "episodes/create" => "episodes#create"
  devise_for :users
  get "pages/home"

  resources :user_episodes

  get "series/search"
  resources :series do
    resources :episodes
  end

  root :to => 'pages#home'

end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %> fade in">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <%= value %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="navbar-default container">
    <div class="navbar-brand">
      EpisodeTracker
    </div>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", '/pages/home' %></li>
          <li><%= link_to "Search", '/series/search' %></li>
          <% if !user_signed_in? %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Sign in", new_user_session_path %></li>
          <% else %>
              <% if can? :manage, :all %>
                  <li><%= link_to "Configure", admin_config_show_path %></li>
              <% end %>
              <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
          <% end %>
        </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
    <head>
      <title>EpisodeTracker</title>
      <%= stylesheet_link_tag    "application", :media => "all" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
    </head>
    <body>
          <%= render 'layouts/header' %>

          <div class="container">
            <div class="flash-holder">
                <%= render 'layouts/flash_messages' %>
            </div>
          <%= yield %>

          </br>
          <hr></hr>
        </div>
    </body>
</html>